name: Github-Actions

on: [push, pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: make docker-image-test
      run: make docker-image-test
